[build]
  command = "npm install --legacy-peer-deps && npm run build:netlify"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SKIP_PREFLIGHT_CHECK = "true"
  CI = "false"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000
  publish = "dist"
  framework = "#custom"